// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfAv0PTjD28ilUWPLy4Qa8cY188KgH64I',
    appId: '1:346013287622:web:eeb7965c2d15f531a243c7',
    messagingSenderId: '346013287622',
    projectId: 'cricapp-58a31',
    authDomain: 'cricapp-58a31.firebaseapp.com',
    storageBucket: 'cricapp-58a31.firebasestorage.app',
    measurementId: 'G-XJFK0C1T51',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzbVD7VIcQs_IzaurqOtpf1zPZzubK2fw',
    appId: '1:346013287622:android:b5ed6f45c6efbb36a243c7',
    messagingSenderId: '346013287622',
    projectId: 'cricapp-58a31',
    storageBucket: 'cricapp-58a31.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1oOH-vTEFaK5MdTqCVkhW9M1Nad7JaZ8',
    appId: '1:346013287622:ios:986278c857d75114a243c7',
    messagingSenderId: '346013287622',
    projectId: 'cricapp-58a31',
    storageBucket: 'cricapp-58a31.firebasestorage.app',
    iosBundleId: 'com.example.cricsonic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1oOH-vTEFaK5MdTqCVkhW9M1Nad7JaZ8',
    appId: '1:346013287622:ios:986278c857d75114a243c7',
    messagingSenderId: '346013287622',
    projectId: 'cricapp-58a31',
    storageBucket: 'cricapp-58a31.firebasestorage.app',
    iosBundleId: 'com.example.cricsonic',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfAv0PTjD28ilUWPLy4Qa8cY188KgH64I',
    appId: '1:346013287622:web:79a1602b8c5fa331a243c7',
    messagingSenderId: '346013287622',
    projectId: 'cricapp-58a31',
    authDomain: 'cricapp-58a31.firebaseapp.com',
    storageBucket: 'cricapp-58a31.firebasestorage.app',
    measurementId: 'G-M27Z0F7YQ4',
  );

}